name: english_order
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.2+2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  google_fonts: ^2.3.2
  provider: ^6.0.2
  hive_flutter: ^1.1.0
  flutter_svg: ^1.0.3
  pdf: ^3.8.0
  printing: ^5.9.0
  image_picker: ^0.8.5+2
  firebase_core: ^1.19.2
  cloud_firestore: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.8
  

flutter:

  uses-material-design: true

  assets:
  - assets/icons/
  - assets/images/
