// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfInpuLePdJOq9CvuDDke-_ZkiKn3Byhc',
    appId: '1:462747645983:web:44f7a13576b10debeefd2a',
    messagingSenderId: '462747645983',
    projectId: 'ezorder-d0db9',
    authDomain: 'ezorder-d0db9.firebaseapp.com',
    storageBucket: 'ezorder-d0db9.appspot.com',
    measurementId: 'G-7RK248Z2BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS1ynGmxnSUQ3ET_OPYtkHdHHlH44OMDg',
    appId: '1:462747645983:android:b5e4eee0a7f7c1a1eefd2a',
    messagingSenderId: '462747645983',
    projectId: 'ezorder-d0db9',
    storageBucket: 'ezorder-d0db9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxQDeMESEB-Uc9aOQDUnbokiKwWZA1jzY',
    appId: '1:462747645983:ios:69635bfec0d77454eefd2a',
    messagingSenderId: '462747645983',
    projectId: 'ezorder-d0db9',
    storageBucket: 'ezorder-d0db9.appspot.com',
    androidClientId: '462747645983-34ddjj55jum1qa25r93j2rsc9olo5m83.apps.googleusercontent.com',
    iosClientId: '462747645983-eb984ckm7qa8aejvao3741lgm13glf4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishOrder',
  );
}
